version: '2'
services:
  postgresql-data:
    image: busybox
    volumes:
      - ./.volumes/postgresql/var/lib/postgresql:/var/lib/postgresql
  gogs-data:
    image: busybox
    volumes:
      - ./.volumes/gogs/home/git/data:/home/git/data

  postgresql:
    image: postgres:9.6.0
    container_name: gogs_db
#    restart: always
    environment:
      - POSTGRES_PASSWORD=gogsdbpassword
    volumes_from:
      - postgresql-data
  gogs: 
    image: gogs/gogs
    ports:
      - "10080:3000"
      - "10022:22"
    volumes_from:
      - gogs-data
